# Generated by Django 5.0.1 on 2024-02-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_room_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.TextField(),
        ),
    ]
