# Generated by Django 5.0.1 on 2024-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_room_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.TextField(default='[]'),
        ),
    ]
